/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProduct: typeof import('./src/components/AddProduct.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CardItem: typeof import('./src/components/CartItem.vue')['default']
    CartDrawer: typeof import('./src/components/CartDrawer.vue')['default']
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    RegistroCliente: typeof import('./src/components/RegistroCliente.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    TOpBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
